fix: crash for NPE toolbar
Sketchware Pro v7.0.0-SNAPSHOT-515e02c (150)
base.apk size: 128 MB (128238178 B)
Locale: en_GB
SDK version: 33
Brand: samsung
Manufacturer: samsung
Model: SM-M325F

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{pro.sketchware/com.besome.sketch.export.ExportProjectActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.Toolbar.setLogo(android.graphics.drawable.Drawable)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8779)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.Toolbar.setLogo(android.graphics.drawable.Drawable)' on a null object reference
	at com.besome.sketch.export.ExportProjectActivity.setupToolbar(ExportProjectActivity.java:152)
	at com.besome.sketch.export.ExportProjectActivity.onCreate(ExportProjectActivity.java:105)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	... 12 more

```