fix: Hackishly catch TextMate language errors on old API levels
The error message would be similar to this:
```
java.lang.NoSuchMethodError: No virtual method getAndSetObject(Ljava/lang/Object;JLjava/lang/Object;)Ljava/lang/Object; in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
```

After looking at the stack trace, it seems to because of tm4e or utility classes in com.google.common. Seems kind of unfixable by the app, so just don't use the TextMate language then.